### ISSUE TITLE
Update References

### ISSUE THREAD

**Issue by JHartzer** [suneeshjacob/ACRoD#2]
There are two references that likely need updating. I cannot find these papers myself, so if you could update these citations with links to the DOI number or preprint archive, that would be much appreciated!

- https://github.com/suneeshjacob/ACRoD/blob/f77170b9131359867dad473d774bea0dd607138e/examples/Jacobian/4R4P_parallel_robot.md?plain=1#L179
- https://github.com/suneeshjacob/ACRoD/blob/f77170b9131359867dad473d774bea0dd607138e/examples/Jacobian/RSSR-SSR_serial-parallel_hybrid_robot%20copy.md?plain=1#L183

**Comment by suneeshjacob** [comment]
Hi, the paper is an unpublished work by the same set of authors, and the cited items are only images. Due to some potential limitations of double blind peer review policies that wouldn't allow prior release of preprints, the authors decided to put this location as primary location for the images and the unpublished work, if published later, would cite this location appropriately. Changes relevant to this, are made in the repository. Hence, I believe this issue is resolved and so I am closing the issue.
