### ISSUE TITLE
JOSS: Paper Comments

### ISSUE THREAD

**Issue by JHartzer** [suneeshjacob/ACRoD#9]
This issue will be a collection of comments regarding the JOSS paper itself.

# Summary
Overall, I believe the summary is good, but think the comparisons to other software should be extended and moved to the statement of need. 

# Statement of Need
Extend the comparison to the other software packages and their limitations to make the statement of need stronger.

Additionally, I wonder if the second paragraph deserves its own section, like`Method` or something similar to group the more technical details together. 

Finally, I encourage you to consider how permanent those hyperlinks will be. Consider that if the location or name of the markdown files are changed, the links will be broken. I would encourage you to include more of the relevant information to the paper in the paper itself, and allow the readme to link to the other documentation.

## Nitpicks
- Use the articles when referring to Jacobians. E.g. "The Jacobian" in the first two sentences.
- Move the GOGU2005427 citation to the end of the sentence.
- "all these studies `are dependent` on human inspection"
- "but either their application is limited to serial manipulators`,` they require human intervention`,` or they are part of computationally expensive simulations"

**Comment by suneeshjacob** [comment]
Thanks for the feedback on the paper, I'll work on them and will update on them once done.

**Comment by suneeshjacob** [comment]
Hi, I made appropriate changes. Regarding adding technical information to the paper, there is a lot of technical information and I think that would occupy a lot of space in the paper. I first planned to put the full-length paper (with all the mathematical jargons) into `paper.md` but after i read [the docs](https://joss.readthedocs.io/en/latest/submitting.html) where it says full length paper is not permitted, i gave up the idea and made this short paper.

Summary of the changes:
1) A subsection is added in the paper for comparison with other software.
2) Moved the second paragraph under a new subsection named 'Method'.
3) Moved many files to a new folder named 'misc', so that the links of the files can stay more permanent.
4) Fixed the nitpicks (thanks)!
